### ISSUE TITLE
An internal error is given when visiting the update page for a deleted entry

### ISSUE THREAD

**Issue by samihsoylu** [samihsoylu/journal#5]
When visiting an update entry page, if the entry does not exist then you will receive an internal error. There was a nice error message before, I need to look into what happened there.

```
Error: Call to a member function getEntryId() on null in /journal/private/cache/templates/e5de10e1590620b058206dae2056122b5ea74ace.php:8
Stack trace:
#0 /journal/vendor/illuminate/filesystem/Filesystem.php(107): require()
#1 /journal/vendor/illuminate/filesystem/Filesystem.php(108): Illuminate\Filesystem\Filesystem::Illuminate\Filesystem\{closure}()
#2 /journal/vendor/illuminate/view/Engines/PhpEngine.php(58): Illuminate\Filesystem\Filesystem->getRequire()
#3 /journal/vendor/illuminate/view/Engines/CompilerEngine.php(61): Illuminate\View\Engines\PhpEngine->evaluatePath()
#4 /journal/vendor/illuminate/view/View.php(139): Illuminate\View\Engines\CompilerEngine->get()
#5 /journal/vendor/illuminate/view/View.php(122): Illuminate\View\View->getContents()
#6 /journal/vendor/illuminate/view/View.php(91): Illuminate\View\View->renderContents()
#7 /journal/vendor/jenssegers/blade/src/Blade.php(47): Illuminate\View\View->render()
#8 /journal/private/lib/Utility/Template.php(88): Jenssegers\Blade\Blade->render()
#9 /journal/private/lib/Controller/Entry.php(229): App\Utility\Template->render()
#10 /journal/private/lib/Router.php(76): App\Controller\Entry->updateView()
#11 /journal/public/index.php(5): App\Router::route()
#12 {main}

Next Illuminate\View\ViewException: Call to a member function getEntryId() on null (View: /journal/private/templates/entry/update.blade.php) in /journal/private/cache/templates/e5de10e1590620b058206dae2056122b5ea74ace.php:8
Stack trace:
#0 /journal/vendor/illuminate/view/Engines/PhpEngine.php(60): Illuminate\View\Engines\CompilerEngine->handleViewException()
#1 /journal/vendor/illuminate/view/Engines/CompilerEngine.php(61): Illuminate\View\Engines\PhpEngine->evaluatePath()
#2 /journal/vendor/illuminate/view/View.php(139): Illuminate\View\Engines\CompilerEngine->get()
#3 /journal/vendor/illuminate/view/View.php(122): Illuminate\View\View->getContents()
#4 /journal/vendor/illuminate/view/View.php(91): Illuminate\View\View->renderContents()
#5 /journal/vendor/jenssegers/blade/src/Blade.php(47): Illuminate\View\View->render()
#6 /journal/private/lib/Utility/Template.php(88): Jenssegers\Blade\Blade->render()
#7 /journal/private/lib/Controller/Entry.php(229): App\Utility\Template->render()
#8 /journal/private/lib/Router.php(76): App\Controller\Entry->updateView()
#9 /journal/public/index.php(5): App\Router::route()
#10 {main}
```

It is also best to check whether all pages redirect properly when incorrect `id` is given in the url.

**Comment by samihsoylu** [comment]
Addressed in #8
